/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graficaatual.formularios.cadastro;

import graficaatual.daos.cadastro.MaterialDAO;
import graficaatual.entidades.Material;
import graficaatual.pesq.cadastro.CnvMaterial;
import graficaatual.utilitarios.Componentes;
import graficaatual.utilitarios.ValidarValor;
import graficaatual.utilitarios.VisualizaRelatorio;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author Marlon
 */
public class FCadMaterial extends javax.swing.JInternalFrame {

    /**
     * Creates new form FCadMaterial
     */
    private Material material;
    private MaterialDAO materialDao = new MaterialDAO();
    private List<Material> lista = null;
    private CnvMaterial cnvMaterial = new CnvMaterial();

    private static FCadMaterial instancia;

    public static FCadMaterial getInstancia() {
        if (instancia == null) {
            instancia = new FCadMaterial();
        }

        return instancia;
    }

    public FCadMaterial() {
        initComponents();

        lista = ObservableCollections.observableList(new LinkedList<Material>());
        Componentes comp2 = new Componentes(lista, false, codMaterial, descMaterial, this, jPanel18, descMaterial.getWidth(), 100);
        comp2.addCol(0, "codMaterial", "Código", 50, Long.class.getName());
        comp2.addCol(1, "descricao", "Nome do Material", 200, String.class.getName());
        comp2.bind();

        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);

        limparTela();

    }

    private void limparTela() {
        btNovo.requestFocus();
        codMaterial.setEnabled(true);
        codMaterial.setText("");

        limparCampos();

        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel18 = new javax.swing.JPanel();
        codMaterial = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        descMaterial = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jTextField49 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jTextField62 = new javax.swing.JTextField();
        jTextField63 = new javax.swing.JTextField();
        jTextField64 = new javax.swing.JTextField();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        tabMaterial = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        ultimo = new javax.swing.JButton();
        proximo = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        inicio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        litro = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        frete = new javax.swing.JTextField();
        precoCustoCompra = new javax.swing.JTextField();
        precoCustoTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboUnidade = new javax.swing.JComboBox<>();
        metragemLinear = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        unidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        estoqueMinimo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        largura = new javax.swing.JTextField();
        altura = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1335, 700));
        setPreferredSize(new java.awt.Dimension(1335, 700));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setMinimumSize(new java.awt.Dimension(1335, 700));
        jPanel18.setPreferredSize(new java.awt.Dimension(1335, 700));
        jPanel18.setLayout(null);

        codMaterial.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        codMaterial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codMaterialFocusLost(evt);
            }
        });
        jPanel18.add(codMaterial);
        codMaterial.setBounds(60, 90, 80, 20);

        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel78.setText("Código ");
        jPanel18.add(jLabel78);
        jLabel78.setBounds(60, 70, 60, 20);

        descMaterial.setBackground(new java.awt.Color(255, 255, 204));
        descMaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descMaterialKeyReleased(evt);
            }
        });
        jPanel18.add(descMaterial);
        descMaterial.setBounds(140, 90, 810, 20);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(null);
        jPanel19.add(jTextField49);
        jTextField49.setBounds(160, 10, 90, 20);

        jTextField50.setBackground(new java.awt.Color(255, 255, 204));
        jPanel19.add(jTextField50);
        jTextField50.setBounds(340, 30, 310, 20);

        jTextField51.setBackground(new java.awt.Color(255, 255, 204));
        jPanel19.add(jTextField51);
        jTextField51.setBounds(160, 50, 490, 20);
        jPanel19.add(jTextField52);
        jTextField52.setBounds(120, 160, 80, 20);
        jPanel19.add(jTextField53);
        jTextField53.setBounds(200, 160, 470, 20);
        jPanel19.add(jTextField54);
        jTextField54.setBounds(780, 160, 140, 20);
        jPanel19.add(jTextField55);
        jTextField55.setBounds(120, 180, 80, 20);
        jPanel19.add(jTextField56);
        jTextField56.setBounds(200, 180, 470, 20);
        jPanel19.add(jTextField57);
        jTextField57.setBounds(780, 180, 140, 20);
        jPanel19.add(jTextField58);
        jTextField58.setBounds(120, 200, 80, 20);
        jPanel19.add(jTextField59);
        jTextField59.setBounds(200, 200, 310, 20);
        jPanel19.add(jTextField60);
        jTextField60.setBounds(780, 200, 140, 20);
        jPanel19.add(jTextField61);
        jTextField61.setBounds(580, 200, 90, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Física", "Juridica" }));
        jPanel19.add(jComboBox3);
        jComboBox3.setBounds(160, 30, 180, 18);

        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel90.setText("UF: ");
        jPanel19.add(jLabel90);
        jLabel90.setBounds(510, 200, 70, 20);

        jLabel91.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel91.setText("CEP: ");
        jPanel19.add(jLabel91);
        jLabel91.setBounds(670, 200, 110, 20);

        jLabel92.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel92.setText("Código: ");
        jPanel19.add(jLabel92);
        jLabel92.setBounds(80, 10, 80, 20);

        jLabel93.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel93.setText("Data Nascimento: ");
        jPanel19.add(jLabel93);
        jLabel93.setBounds(650, 70, 140, 20);

        jLabel94.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel94.setText("Número: ");
        jPanel19.add(jLabel94);
        jLabel94.setBounds(670, 160, 110, 20);

        jLabel95.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel95.setText("Insc. Estadual:");
        jPanel19.add(jLabel95);
        jLabel95.setBounds(650, 50, 140, 20);

        jLabel96.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel96.setText("Bairro: ");
        jPanel19.add(jLabel96);
        jLabel96.setBounds(20, 180, 100, 20);

        jLabel97.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel97.setText("Logradouro: ");
        jPanel19.add(jLabel97);
        jLabel97.setBounds(20, 160, 100, 20);

        jLabel98.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel98.setText("Complemento: ");
        jPanel19.add(jLabel98);
        jLabel98.setBounds(670, 180, 110, 20);

        jLabel99.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel99.setText("Cidade: ");
        jPanel19.add(jLabel99);
        jLabel99.setBounds(20, 200, 100, 20);

        jLabel100.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel100.setBorder(javax.swing.BorderFactory.createTitledBorder("Endeço:"));
        jPanel19.add(jLabel100);
        jLabel100.setBounds(10, 130, 920, 110);

        jLabel101.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel101.setText("CPF/CNPJ: ");
        jPanel19.add(jLabel101);
        jLabel101.setBounds(80, 30, 80, 20);
        jPanel19.add(jTextField62);
        jTextField62.setBounds(790, 70, 130, 20);
        jPanel19.add(jTextField63);
        jTextField63.setBounds(790, 30, 130, 20);
        jPanel19.add(jTextField64);
        jTextField64.setBounds(790, 50, 130, 20);

        jLabel102.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel102.setText("Nome/Razão Socia: ");
        jPanel19.add(jLabel102);
        jLabel102.setBounds(10, 50, 150, 20);

        jLabel103.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel103.setText("Insc. Munícipal:");
        jPanel19.add(jLabel103);
        jLabel103.setBounds(650, 30, 140, 20);

        jPanel18.add(jPanel19);
        jPanel19.setBounds(0, 0, 0, 0);

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/NOVO2.png"))); // NOI18N
        btNovo.setText("Novo Cadastro");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jPanel18.add(btNovo);
        btNovo.setBounds(30, 250, 180, 39);

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar2.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel18.add(btSalvar);
        btSalvar.setBounds(210, 250, 180, 39);

        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excuir2.png"))); // NOI18N
        btExcluir.setText("Deletar");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel18.add(btExcluir);
        btExcluir.setBounds(390, 250, 180, 39);

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/SAIR2.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jPanel18.add(btSair);
        btSair.setBounds(750, 250, 180, 39);

        tabMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Material", "M. Linear (m)", "Larg. (m)", "Alt. (m)", "Unidades", "Peso (kg)", "Litros (L)", "Frete (R$)", "P. Compra (R$)", "Custo Total (R$)", "Est. Mínimo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMaterialMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(tabMaterial);
        if (tabMaterial.getColumnModel().getColumnCount() > 0) {
            tabMaterial.getColumnModel().getColumn(0).setPreferredWidth(2);
            tabMaterial.getColumnModel().getColumn(1).setPreferredWidth(140);
            tabMaterial.getColumnModel().getColumn(2).setPreferredWidth(10);
            tabMaterial.getColumnModel().getColumn(3).setPreferredWidth(10);
            tabMaterial.getColumnModel().getColumn(4).setPreferredWidth(10);
            tabMaterial.getColumnModel().getColumn(5).setPreferredWidth(10);
            tabMaterial.getColumnModel().getColumn(6).setPreferredWidth(10);
            tabMaterial.getColumnModel().getColumn(7).setPreferredWidth(10);
            tabMaterial.getColumnModel().getColumn(8).setPreferredWidth(10);
            tabMaterial.getColumnModel().getColumn(9).setPreferredWidth(35);
            tabMaterial.getColumnModel().getColumn(10).setPreferredWidth(45);
            tabMaterial.getColumnModel().getColumn(11).setPreferredWidth(20);
        }

        jPanel18.add(jScrollPane11);
        jScrollPane11.setBounds(20, 320, 930, 240);

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));

        ultimo.setText(">>||");
        ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoActionPerformed(evt);
            }
        });

        proximo.setText(">>");
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });

        anterior.setText("<<");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        inicio.setText("||<<");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(anterior)
                        .addComponent(inicio))
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(proximo)
                        .addComponent(ultimo)))
                .addGap(23, 23, 23))
        );

        jPanel18.add(jPanel20);
        jPanel20.setBounds(280, 580, 430, 40);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE MATERIAL");
        jPanel18.add(jLabel1);
        jLabel1.setBounds(-110, 0, 1260, 70);

        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel80.setText("Material");
        jPanel18.add(jLabel80);
        jLabel80.setBounds(140, 70, 70, 20);

        jLabel2.setText("Unidade de Medida");
        jPanel18.add(jLabel2);
        jLabel2.setBounds(60, 120, 140, 14);

        jLabel3.setText("X");
        jPanel18.add(jLabel3);
        jLabel3.setBounds(432, 140, 10, 20);

        jLabel4.setText("Litros (L)");
        jPanel18.add(jLabel4);
        jLabel4.setBounds(820, 120, 130, 14);

        jLabel5.setText("Peso (Kg)");
        jPanel18.add(jLabel5);
        jLabel5.setBounds(670, 120, 80, 14);

        litro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        litro.setText("0,00");
        litro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                litroFocusLost(evt);
            }
        });
        litro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                litroActionPerformed(evt);
            }
        });
        jPanel18.add(litro);
        litro.setBounds(820, 140, 130, 20);

        peso.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        peso.setText("0,00");
        peso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pesoFocusLost(evt);
            }
        });
        peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoActionPerformed(evt);
            }
        });
        jPanel18.add(peso);
        peso.setBounds(670, 140, 130, 20);

        jLabel6.setText("Custo Frete (R$)");
        jPanel18.add(jLabel6);
        jLabel6.setBounds(60, 170, 140, 20);

        frete.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        frete.setText("0,00");
        frete.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                freteFocusLost(evt);
            }
        });
        frete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freteActionPerformed(evt);
            }
        });
        jPanel18.add(frete);
        frete.setBounds(60, 190, 130, 20);

        precoCustoCompra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        precoCustoCompra.setText("0,00");
        precoCustoCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                precoCustoCompraFocusLost(evt);
            }
        });
        precoCustoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoCustoCompraActionPerformed(evt);
            }
        });
        jPanel18.add(precoCustoCompra);
        precoCustoCompra.setBounds(220, 190, 130, 20);

        precoCustoTotal.setBackground(new java.awt.Color(255, 255, 204));
        precoCustoTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        precoCustoTotal.setText("0,00");
        jPanel18.add(precoCustoTotal);
        precoCustoTotal.setBounds(370, 190, 130, 20);

        jLabel8.setText("Preço de Compra (R$)");
        jPanel18.add(jLabel8);
        jLabel8.setBounds(220, 170, 130, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Preço de Custo Total");
        jPanel18.add(jLabel9);
        jLabel9.setBounds(370, 170, 150, 14);

        comboUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metro Linear (m)", "Metro Quadrado (m²)", "Unidade (un)", "Quilo (kg)", "Litro (L)"  }));
        comboUnidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboUnidadeItemStateChanged(evt);
            }
        });
        jPanel18.add(comboUnidade);
        comboUnidade.setBounds(60, 140, 130, 20);

        metragemLinear.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        metragemLinear.setText("0,00");
        jPanel18.add(metragemLinear);
        metragemLinear.setBounds(220, 140, 130, 20);

        jLabel11.setText("Metragem Linear (m)");
        jPanel18.add(jLabel11);
        jLabel11.setBounds(220, 120, 120, 14);

        unidade.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        unidade.setText("0");
        jPanel18.add(unidade);
        unidade.setBounds(520, 140, 130, 20);

        jLabel12.setText("Unidade (un)");
        jPanel18.add(jLabel12);
        jLabel12.setBounds(520, 120, 100, 14);

        estoqueMinimo.setBackground(new java.awt.Color(255, 255, 204));
        estoqueMinimo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel18.add(estoqueMinimo);
        estoqueMinimo.setBounds(520, 190, 130, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Estoque Mínimo");
        jPanel18.add(jLabel13);
        jLabel13.setBounds(520, 170, 130, 14);

        largura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        largura.setText("0,00");
        jPanel18.add(largura);
        largura.setBounds(370, 140, 60, 20);

        altura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        altura.setText("0,00");
        jPanel18.add(altura);
        altura.setBounds(440, 140, 60, 20);

        jLabel7.setText("Largura (m)");
        jPanel18.add(jLabel7);
        jLabel7.setBounds(370, 120, 70, 14);

        jLabel10.setText("Altura (m)");
        jPanel18.add(jLabel10);
        jLabel10.setBounds(440, 120, 70, 14);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imprimir2.png"))); // NOI18N
        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton1);
        jButton1.setBounds(570, 250, 180, 39);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1319, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 1209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 110, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codMaterialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codMaterialFocusLost
        try {
            material = materialDao.getPorCodigo(ValidarValor.getLong(codMaterial.getText()));
            if (material != null) {
                carregarCampos(material);
            } else {
                limparCampos();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_codMaterialFocusLost

    private void descMaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descMaterialKeyReleased
        try {

            List<Material> merged = materialDao.getList(15, "select e from Material e where lower (trim(e.descricao))   like ?1 order by e.descricao asc", (descMaterial.getText().trim().toLowerCase() + "%"));
            lista.clear();
            lista.addAll(merged);
        } catch (Exception e) {
            System.out.println("Ocorreu um erro ao tentar pesquisar materials. Erro: " + e);
        }
    }//GEN-LAST:event_descMaterialKeyReleased

    private void atualizarTabela() {
        try {
            DefaultTableModel model = (DefaultTableModel) tabMaterial.getModel();
            removeLinhas(tabMaterial);

            List<Material> listaAux = materialDao.getList();
            if (listaAux.size() > 0) {
                model.setNumRows(0);

                for (Material m : listaAux) {

                    Object o[] = new Object[]{
                        m.getCodMaterial(),
                        m.getDescricao(),
                        /*  getDescricaoUnidade(m.getUnidade()),*/
                        m.getMetragemLinear() != null ? ValidarValor.getDouble(m.getMetragemLinear()) : null,
                        m.getLargura() != null ? ValidarValor.getDouble(m.getLargura()) : null,
                        m.getAltura() != null ? ValidarValor.getDouble(m.getAltura()) : null,
                        m.getUnidade() != null ? ValidarValor.getDouble(m.getUnidade()) : null,
                        m.getPeso() != null ? ValidarValor.getDouble(m.getPeso()) : null,
                        m.getLitro() != null ? ValidarValor.getDouble(m.getLitro()) : null,
                        m.getFrete() != null ? ValidarValor.getDouble(m.getFrete()) : null,
                        ValidarValor.getDouble(m.getPrecoCompra()),
                        ValidarValor.getDouble(m.getPrecoCustoTotal()),
                        ValidarValor.getDouble(m.getEstoqueMinimo()),};

                    model.addRow(o);
                }
            }
            tabMaterial.setModel(model);
        } catch (Exception e) {
            removeLinhas(tabMaterial);
            JOptionPane.showMessageDialog(null, "Erro ao atualizar lista de materiais cadastrados. Erro: " + e);
            e.printStackTrace();

        }
    }

    private String getDescricaoUnidade(int op) {

        switch (op) {
            case 0:
                return "Metro (linear)";
            case 1:
                return "Metro Quadrado (m²)";
            case 2:
                return "Unidade (un)";
            case 3:
                return "Quilo (kg)";
            case 4:
                return "Litro (L)";

            default:
                return "";
        }
    }

    public static void removeLinhas(JTable table) {
        int n = table.getRowCount();

        DefaultTableModel model = (DefaultTableModel) table.getModel();

        for (int i = n - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }


    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        try {
            descMaterial.requestFocus();
            codMaterial.setText("" + materialDao.getNextItem());
            //   codMaterial.setEnabled(false);

            limparCampos();
            descMaterial.requestFocus();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btNovoActionPerformed

    private void limparCampos() {
        descMaterial.setText("");
        material = null;

        comboUnidade.setSelectedIndex(0);

        metragemLinear.setEnabled(true);
        largura.setEnabled(false);
        altura.setEnabled(false);
        unidade.setEnabled(false);
        litro.setEnabled(false);
        peso.setEnabled(false);

        metragemLinear.setText("0,00");
        largura.setText("0,00");
        altura.setText("0,00");
        unidade.setText("0");
        peso.setText("0,00");
        litro.setText("0,00");
        estoqueMinimo.setText("0,00");
        frete.setText("0,00");

        precoCustoCompra.setText("0,00");
        precoCustoTotal.setText("0,00");

    }

    private void carregarCampos(Material m) {

        if (m != null) {
            material = m;
            descMaterial.setText(m.getDescricao());
            comboUnidade.setSelectedIndex(m.getUnidadeMedida());

            metragemLinear.setText(m.getMetragemLinear() == null ? "0,00" : ValidarValor.getDouble(m.getMetragemLinear()));
            largura.setText(m.getLargura() == null ? "0,00" : ValidarValor.getDouble(m.getLargura()));
            altura.setText(m.getAltura() == null ? "0,00" : ValidarValor.getDouble(m.getAltura()));
            unidade.setText(m.getUnidade() == null ? "0" : ValidarValor.getDouble(m.getUnidade()));
            peso.setText(m.getPeso() == null ? "0,00" : ValidarValor.getDouble(m.getPeso()));
            litro.setText(m.getLitro() == null ? "0,00" : ValidarValor.getDouble(m.getLitro()));

            frete.setText(m.getFrete() == null ? "0,00" : ValidarValor.getDouble(m.getFrete()));
            precoCustoCompra.setText(ValidarValor.getDouble(m.getPrecoCompra()));
            precoCustoTotal.setText(ValidarValor.getDouble(m.getPrecoCustoTotal()));
            estoqueMinimo.setText(ValidarValor.getDouble(m.getEstoqueMinimo()));
        }
    }

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        try {

            if (estoqueMinimo.getText() == null || estoqueMinimo.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Insíra uma quantidade de estoque mínimo para este material!");
            } else {

                if (material == null) {
                    material = new Material();
                    material.setDataCadastro(new Date());
                    material.setDataAtualizacao(new Date());
                } else {
                    material.setDataAtualizacao(new Date());
                }

                atualizaPrecoCustoTotal();

                material.setCodMaterial(Long.parseLong(codMaterial.getText()));
                material.setDescricao(descMaterial.getText());

                material.setUnidadeMedida(comboUnidade.getSelectedIndex());

                material.setMetragemLinear((ValidarValor.getDouble(metragemLinear.getText()) > 0 ? ValidarValor.getDouble(metragemLinear.getText()) : null));
                material.setLargura((ValidarValor.getDouble(largura.getText()) > 0 ? ValidarValor.getDouble(largura.getText()) : null));
                material.setAltura(ValidarValor.getDouble(altura.getText()) > 0 ? ValidarValor.getDouble(altura.getText()) : null);
                material.setUnidade(ValidarValor.getDouble(unidade.getText()) > 0 ? ValidarValor.getDouble(unidade.getText()) : null);
                material.setPeso(ValidarValor.getDouble(peso.getText()) > 0 ? ValidarValor.getDouble(peso.getText()) : null);
                material.setLitro(ValidarValor.getDouble(litro.getText()) > 0 ? ValidarValor.getDouble(litro.getText()) : null);

                material.setFrete(ValidarValor.getDouble(frete.getText()) > 0 ? ValidarValor.getArredondamento(ValidarValor.getDouble(frete.getText())) : null);

                material.setPrecoCompra(ValidarValor.getArredondamento(ValidarValor.getDouble(precoCustoCompra.getText())));
                material.setPrecoCustoTotal(ValidarValor.getArredondamento(ValidarValor.getDouble(precoCustoTotal.getText())));
                material.setEstoqueMinimo(ValidarValor.getArredondamento(ValidarValor.getDouble(estoqueMinimo.getText())));

                if (materialDao.salvar(material) != null) {
                    JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
                    limparTela();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao salvar material. Erro: " + e);
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        try {
            if (material == null) {
                throw new Exception("Erro: material inválido!");
            }
            int op = 0;
            JOptionPane.showConfirmDialog(null, "Deseja realmente excluir material selecionado?", "CONFIRMAÇÃO DE EXCLUSÃO", op);

            // considerando 0 como sim
            if (op == 0) {

                materialDao.delete(material);
                limparTela();

            } else {
                return;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir material. Erro: " + e);
        }
    }//GEN-LAST:event_btExcluirActionPerformed


    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        limparTela();
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void tabMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMaterialMouseClicked
        if (evt.getClickCount() > 1) {
            codMaterial.setText(("" + tabMaterial.getValueAt(tabMaterial.getSelectedRow(), 0)));
            codMaterialFocusLost(null);
            descMaterial.requestFocus();
        }
    }//GEN-LAST:event_tabMaterialMouseClicked

    private void ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoActionPerformed
        try {
            cnvMaterial.ultimo();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ultimoActionPerformed

    private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed
        try {
            cnvMaterial.proximo();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_proximoActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        try {
            cnvMaterial.anterior();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_anteriorActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        try {
            cnvMaterial.primeiro();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_inicioActionPerformed

    private void litroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_litroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_litroActionPerformed

    private void pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoActionPerformed

    private void comboUnidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboUnidadeItemStateChanged
        try {
            switch (comboUnidade.getSelectedIndex()) {
                case 0:

                    metragemLinear.setEnabled(true);
                    largura.setEnabled(false);
                    altura.setEnabled(false);
                    unidade.setEnabled(false);
                    peso.setEnabled(false);
                    litro.setEnabled(false);

                    largura.setText("0,00");
                    altura.setText("0,00");
                    unidade.setText("0");
                    peso.setText("0,00");
                    litro.setText("0,00");
                    frete.setText("0,00");
                    break;
                case 1:

                    largura.setEnabled(true);
                    altura.setEnabled(true);
                    metragemLinear.setEnabled(false);
                    unidade.setEnabled(false);
                    peso.setEnabled(false);
                    litro.setEnabled(false);

                    metragemLinear.setText("0,00");
                    unidade.setText("0");
                    peso.setText("0,00");
                    litro.setText("0,00");
                    frete.setText("0,00");
                    break;
                case 2:

                    metragemLinear.setEnabled(false);
                    largura.setEnabled(false);
                    altura.setEnabled(false);
                    unidade.setEnabled(true);
                    peso.setEnabled(false);
                    litro.setEnabled(false);

                    metragemLinear.setText("0,00");
                    largura.setText("0,00");
                    altura.setText("0,00");
                    peso.setText("0,00");
                    litro.setText("0,00");
                    frete.setText("0,00");

                    break;

                case 3:

                    metragemLinear.setEnabled(false);
                    largura.setEnabled(false);
                    altura.setEnabled(false);
                    unidade.setEnabled(false);
                    peso.setEnabled(true);
                    litro.setEnabled(false);

                    metragemLinear.setText("0,00");
                    largura.setText("0,00");
                    altura.setText("0,00");
                    unidade.setText("0");
                    litro.setText("0,00");

                    frete.setText("0,00");

                    break;

                case 4:

                    metragemLinear.setEnabled(false);
                    largura.setEnabled(false);
                    altura.setEnabled(false);
                    unidade.setEnabled(false);
                    peso.setEnabled(false);
                    litro.setEnabled(true);

                    metragemLinear.setText("0,00");
                    largura.setText("0,00");
                    altura.setText("0,00");
                    unidade.setText("0");
                    peso.setText("0,00");
                    frete.setText("0,00");

                    break;
                default:
                    break;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_comboUnidadeItemStateChanged

    private void precoCustoCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precoCustoCompraFocusLost
        atualizaPrecoCustoTotal();
    }//GEN-LAST:event_precoCustoCompraFocusLost

    private void freteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_freteActionPerformed

    private void precoCustoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoCustoCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoCustoCompraActionPerformed

    private void freteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_freteFocusLost
        atualizaPrecoCustoTotal();
    }//GEN-LAST:event_freteFocusLost

    private void litroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_litroFocusLost
        atualizaPrecoCustoTotal();
    }//GEN-LAST:event_litroFocusLost

    private void pesoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pesoFocusLost
        atualizaPrecoCustoTotal();
    }//GEN-LAST:event_pesoFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String sql = "select codmaterial, descricao , case unidademedida when 0 then 'Metro (linear)' when 1 then 'Metro Quadrado(m²)' when 2 then 'Unidade (un)' when 3 then 'Peso (kg)' when 4 then 'Litros (l)' end as unidademedida, metragemlinear, altura,  largura, unidade,  peso, litro,  frete,  precocompra, precocustototal, estoqueminimo   from material order by descricao asc";

            new VisualizaRelatorio().visRel("graficaatual/relatorios/arquivos/material.jasper", "RELATÓRIO DE MATERIAIS", null, sql);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao gerar relatório de Materiais! \n " + e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void atualizaPrecoCustoTotal() {
        try {

            Double preco = 0.00;

            preco = (ValidarValor.getArredondamento((Double.parseDouble(frete.getText().replaceAll(",", ".")) + Double.parseDouble(precoCustoCompra.getText().replaceAll(",", ".")))));
            precoCustoTotal.setText(ValidarValor.getDouble(preco));

        } catch (Exception e) {
            e.printStackTrace();
            precoCustoTotal.setText("0,00");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altura;
    private javax.swing.JButton anterior;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField codMaterial;
    private javax.swing.JComboBox<String> comboUnidade;
    private javax.swing.JTextField descMaterial;
    private javax.swing.JTextField estoqueMinimo;
    private javax.swing.JTextField frete;
    private javax.swing.JButton inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField largura;
    private javax.swing.JTextField litro;
    private javax.swing.JTextField metragemLinear;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField precoCustoCompra;
    private javax.swing.JTextField precoCustoTotal;
    private javax.swing.JButton proximo;
    private javax.swing.JTable tabMaterial;
    private javax.swing.JButton ultimo;
    private javax.swing.JTextField unidade;
    // End of variables declaration//GEN-END:variables
}
