/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graficaatual.formularios.cadastro;

import graficaatual.daos.cadastro.ComposicaoProdutoDAO;
import graficaatual.daos.cadastro.MaterialDAO;
import graficaatual.daos.cadastro.ProdutoDAO;
import graficaatual.entidades.ComposicaoProduto;
import graficaatual.entidades.Material;
import graficaatual.entidades.Produto;
import graficaatual.pesq.cadastro.CnvProduto;
import graficaatual.utilitarios.Componentes;
import graficaatual.utilitarios.ValidarValor;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author Marlon
 */
public class FCadProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form FCadProduto
     */
    private Produto produto;
    private Material material;
    private ComposicaoProduto composicaoProduto;
    private ComposicaoProdutoDAO composicaoDao = new ComposicaoProdutoDAO();
    private ProdutoDAO produtoDao = new ProdutoDAO();
    private MaterialDAO materialDao = new MaterialDAO();
    private List<Produto> lista = null;
    private List<Material> listaMaterial = null;
    private CnvProduto cnvProduto = new CnvProduto();

    private static FCadProduto instancia;

    public static FCadProduto getInstancia() {
        if (instancia == null) {
            instancia = new FCadProduto();
        }

        return instancia;
    }

    public FCadProduto() {
        initComponents();

        lista = ObservableCollections.observableList(new LinkedList<Produto>());
        Componentes comp2 = new Componentes(lista, false, codProduto, descProduto, this, jPanel18, descProduto.getWidth(), 100);
        comp2.addCol(0, "codProduto", "Código", 50, Long.class.getName());
        comp2.addCol(1, "descricao", "Nome do Produto", 200, String.class.getName());
        comp2.bind();

        listaMaterial = ObservableCollections.observableList(new LinkedList<Material>());
        Componentes comp3 = new Componentes(listaMaterial, false, codMaterial, descMaterial, this, jPanel18, descMaterial.getWidth(), 100);
        comp2.addCol(0, "codMaterial", "Código", 50, Long.class.getName());
        comp2.addCol(1, "descricao", "Nome do Material", 200, String.class.getName());
        comp2.bind();

    }

    private void limparTela() {

        valorUnitario.setEditable(false);
        custoServico.setEditable(false);
        custoProduto.setEditable(false);
        msgMaterial.setVisible(false);
        limparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel18 = new javax.swing.JPanel();
        codProduto = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        descProduto = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jTextField49 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jTextField62 = new javax.swing.JTextField();
        jTextField63 = new javax.swing.JTextField();
        jTextField64 = new javax.swing.JTextField();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabComposicao = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        custoProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        maoDeObra = new javax.swing.JTextField();
        custoEmpresa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        custoServico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        margemLucro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        valorUnitario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        codMaterial = new javax.swing.JTextField();
        descMaterial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        quantidade = new javax.swing.JTextField();
        btAddMaterial = new javax.swing.JButton();
        msgMaterial = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jTextField65 = new javax.swing.JTextField();
        jTextField66 = new javax.swing.JTextField();
        jTextField67 = new javax.swing.JTextField();
        jTextField68 = new javax.swing.JTextField();
        jTextField69 = new javax.swing.JTextField();
        jTextField70 = new javax.swing.JTextField();
        jTextField71 = new javax.swing.JTextField();
        jTextField72 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jTextField74 = new javax.swing.JTextField();
        jTextField75 = new javax.swing.JTextField();
        jTextField76 = new javax.swing.JTextField();
        jTextField77 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jTextField78 = new javax.swing.JTextField();
        jTextField79 = new javax.swing.JTextField();
        jTextField80 = new javax.swing.JTextField();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        tabProduto = new javax.swing.JTable();
        jPanel23 = new javax.swing.JPanel();
        ultimo1 = new javax.swing.JButton();
        proximo1 = new javax.swing.JButton();
        anterior1 = new javax.swing.JButton();
        inicio1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(null);

        codProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codProdutoFocusLost(evt);
            }
        });
        jPanel18.add(codProduto);
        codProduto.setBounds(60, 90, 80, 20);

        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel78.setText("Código ");
        jPanel18.add(jLabel78);
        jLabel78.setBounds(60, 70, 60, 20);

        descProduto.setBackground(new java.awt.Color(255, 255, 204));
        descProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descProdutoKeyReleased(evt);
            }
        });
        jPanel18.add(descProduto);
        descProduto.setBounds(140, 90, 810, 20);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(null);
        jPanel19.add(jTextField49);
        jTextField49.setBounds(160, 10, 90, 20);

        jTextField50.setBackground(new java.awt.Color(255, 255, 204));
        jPanel19.add(jTextField50);
        jTextField50.setBounds(340, 30, 310, 20);

        jTextField51.setBackground(new java.awt.Color(255, 255, 204));
        jPanel19.add(jTextField51);
        jTextField51.setBounds(160, 50, 490, 20);
        jPanel19.add(jTextField52);
        jTextField52.setBounds(120, 160, 80, 20);
        jPanel19.add(jTextField53);
        jTextField53.setBounds(200, 160, 470, 20);
        jPanel19.add(jTextField54);
        jTextField54.setBounds(780, 160, 140, 20);
        jPanel19.add(jTextField55);
        jTextField55.setBounds(120, 180, 80, 20);
        jPanel19.add(jTextField56);
        jTextField56.setBounds(200, 180, 470, 20);
        jPanel19.add(jTextField57);
        jTextField57.setBounds(780, 180, 140, 20);
        jPanel19.add(jTextField58);
        jTextField58.setBounds(120, 200, 80, 20);
        jPanel19.add(jTextField59);
        jTextField59.setBounds(200, 200, 310, 20);
        jPanel19.add(jTextField60);
        jTextField60.setBounds(780, 200, 140, 20);
        jPanel19.add(jTextField61);
        jTextField61.setBounds(580, 200, 90, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Física", "Juridica" }));
        jPanel19.add(jComboBox3);
        jComboBox3.setBounds(160, 30, 180, 18);

        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel90.setText("UF: ");
        jPanel19.add(jLabel90);
        jLabel90.setBounds(510, 200, 70, 20);

        jLabel91.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel91.setText("CEP: ");
        jPanel19.add(jLabel91);
        jLabel91.setBounds(670, 200, 110, 20);

        jLabel92.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel92.setText("Código: ");
        jPanel19.add(jLabel92);
        jLabel92.setBounds(80, 10, 80, 20);

        jLabel93.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel93.setText("Data Nascimento: ");
        jPanel19.add(jLabel93);
        jLabel93.setBounds(650, 70, 140, 20);

        jLabel94.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel94.setText("Número: ");
        jPanel19.add(jLabel94);
        jLabel94.setBounds(670, 160, 110, 20);

        jLabel95.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel95.setText("Insc. Estadual:");
        jPanel19.add(jLabel95);
        jLabel95.setBounds(650, 50, 140, 20);

        jLabel96.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel96.setText("Bairro: ");
        jPanel19.add(jLabel96);
        jLabel96.setBounds(20, 180, 100, 20);

        jLabel97.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel97.setText("Logradouro: ");
        jPanel19.add(jLabel97);
        jLabel97.setBounds(20, 160, 100, 20);

        jLabel98.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel98.setText("Complemento: ");
        jPanel19.add(jLabel98);
        jLabel98.setBounds(670, 180, 110, 20);

        jLabel99.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel99.setText("Cidade: ");
        jPanel19.add(jLabel99);
        jLabel99.setBounds(20, 200, 100, 20);

        jLabel100.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel100.setBorder(javax.swing.BorderFactory.createTitledBorder("Endeço:"));
        jPanel19.add(jLabel100);
        jLabel100.setBounds(10, 130, 920, 110);

        jLabel101.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel101.setText("CPF/CNPJ: ");
        jPanel19.add(jLabel101);
        jLabel101.setBounds(80, 30, 80, 20);
        jPanel19.add(jTextField62);
        jTextField62.setBounds(790, 70, 130, 20);
        jPanel19.add(jTextField63);
        jTextField63.setBounds(790, 30, 130, 20);
        jPanel19.add(jTextField64);
        jTextField64.setBounds(790, 50, 130, 20);

        jLabel102.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel102.setText("Nome/Razão Socia: ");
        jPanel19.add(jLabel102);
        jLabel102.setBounds(10, 50, 150, 20);

        jLabel103.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel103.setText("Insc. Munícipal:");
        jPanel19.add(jLabel103);
        jLabel103.setBounds(650, 30, 140, 20);

        jPanel18.add(jPanel19);
        jPanel19.setBounds(0, 0, 0, 0);

        btNovo.setText("Novo Cadastro");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jPanel18.add(btNovo);
        btNovo.setBounds(140, 500, 180, 23);

        btSalvar.setText("Salvar/Atualizar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel18.add(btSalvar);
        btSalvar.setBounds(320, 500, 180, 23);

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel18.add(btExcluir);
        btExcluir.setBounds(500, 500, 180, 23);

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jPanel18.add(btSair);
        btSair.setBounds(680, 500, 180, 23);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE PRODUTO");
        jPanel18.add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 70);

        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel80.setText("Produto");
        jPanel18.add(jLabel80);
        jLabel80.setBounds(140, 70, 70, 20);

        tabComposicao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Material", "Material", "Valor Unitário (R$)", "Quantidade", "Total (R$)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabComposicao);

        jPanel18.add(jScrollPane1);
        jScrollPane1.setBounds(20, 180, 930, 220);

        jLabel2.setText("Custo Produto ( m²)");
        jPanel18.add(jLabel2);
        jLabel2.setBounds(20, 440, 110, 14);

        custoProduto.setText("0,00");
        jPanel18.add(custoProduto);
        custoProduto.setBounds(20, 460, 130, 20);

        jLabel3.setText("Mão De Obra (m²)");
        jPanel18.add(jLabel3);
        jLabel3.setBounds(160, 440, 90, 14);

        maoDeObra.setText("0,00");
        maoDeObra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                maoDeObraFocusLost(evt);
            }
        });
        jPanel18.add(maoDeObra);
        maoDeObra.setBounds(160, 460, 130, 20);

        custoEmpresa.setText("0,00");
        custoEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                custoEmpresaFocusLost(evt);
            }
        });
        jPanel18.add(custoEmpresa);
        custoEmpresa.setBounds(300, 460, 130, 20);

        jLabel4.setText("Custo Empresa ( m² / hora)");
        jPanel18.add(jLabel4);
        jLabel4.setBounds(300, 440, 140, 14);

        jLabel5.setText("Custo do Serviço m²");
        jPanel18.add(jLabel5);
        jLabel5.setBounds(440, 440, 140, 14);

        custoServico.setBackground(new java.awt.Color(255, 255, 204));
        custoServico.setText("0,00");
        jPanel18.add(custoServico);
        custoServico.setBounds(440, 460, 130, 20);

        jLabel6.setText("Margem de Lucro (%)");
        jPanel18.add(jLabel6);
        jLabel6.setBounds(580, 440, 130, 14);

        margemLucro.setBackground(new java.awt.Color(255, 255, 204));
        margemLucro.setText("0");
        margemLucro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                margemLucroFocusLost(evt);
            }
        });
        jPanel18.add(margemLucro);
        margemLucro.setBounds(580, 460, 130, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Valor Unitário (m²)");
        jPanel18.add(jLabel7);
        jLabel7.setBounds(780, 440, 150, 15);

        valorUnitario.setBackground(new java.awt.Color(255, 255, 204));
        valorUnitario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        valorUnitario.setText("0,00");
        jPanel18.add(valorUnitario);
        valorUnitario.setBounds(780, 460, 130, 21);

        jLabel8.setText("Cód. Material");
        jPanel18.add(jLabel8);
        jLabel8.setBounds(60, 120, 80, 14);

        codMaterial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codMaterialFocusLost(evt);
            }
        });
        jPanel18.add(codMaterial);
        codMaterial.setBounds(60, 140, 80, 20);

        descMaterial.setBackground(new java.awt.Color(255, 255, 204));
        descMaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descMaterialKeyReleased(evt);
            }
        });
        jPanel18.add(descMaterial);
        descMaterial.setBounds(140, 140, 440, 20);

        jLabel9.setText("Material");
        jPanel18.add(jLabel9);
        jLabel9.setBounds(140, 120, 100, 14);

        jLabel10.setText("Quantidade");
        jPanel18.add(jLabel10);
        jLabel10.setBounds(590, 120, 100, 14);

        quantidade.setText("0,00");
        quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeActionPerformed(evt);
            }
        });
        jPanel18.add(quantidade);
        quantidade.setBounds(590, 140, 100, 20);

        btAddMaterial.setText("Adicionar Material Em Composição");
        btAddMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddMaterialActionPerformed(evt);
            }
        });
        jPanel18.add(btAddMaterial);
        btAddMaterial.setBounds(700, 140, 250, 23);

        msgMaterial.setForeground(new java.awt.Color(255, 0, 0));
        msgMaterial.setText("* Produto ainda não foi salvo. Informe os valores abaixo e clique em salvar!");
        jPanel18.add(msgMaterial);
        msgMaterial.setBounds(20, 410, 400, 14);

        jTabbedPane1.addTab("Cadastrar", jPanel18);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(null);

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setLayout(null);
        jPanel22.add(jTextField65);
        jTextField65.setBounds(160, 10, 90, 20);

        jTextField66.setBackground(new java.awt.Color(255, 255, 204));
        jPanel22.add(jTextField66);
        jTextField66.setBounds(340, 30, 310, 20);

        jTextField67.setBackground(new java.awt.Color(255, 255, 204));
        jPanel22.add(jTextField67);
        jTextField67.setBounds(160, 50, 490, 20);
        jPanel22.add(jTextField68);
        jTextField68.setBounds(120, 160, 80, 20);
        jPanel22.add(jTextField69);
        jTextField69.setBounds(200, 160, 470, 20);
        jPanel22.add(jTextField70);
        jTextField70.setBounds(780, 160, 140, 20);
        jPanel22.add(jTextField71);
        jTextField71.setBounds(120, 180, 80, 20);
        jPanel22.add(jTextField72);
        jTextField72.setBounds(200, 180, 470, 20);
        jPanel22.add(jTextField73);
        jTextField73.setBounds(780, 180, 140, 20);
        jPanel22.add(jTextField74);
        jTextField74.setBounds(120, 200, 80, 20);
        jPanel22.add(jTextField75);
        jTextField75.setBounds(200, 200, 310, 20);
        jPanel22.add(jTextField76);
        jTextField76.setBounds(780, 200, 140, 20);
        jPanel22.add(jTextField77);
        jTextField77.setBounds(580, 200, 90, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Física", "Juridica" }));
        jPanel22.add(jComboBox4);
        jComboBox4.setBounds(160, 30, 180, 18);

        jLabel104.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel104.setText("UF: ");
        jPanel22.add(jLabel104);
        jLabel104.setBounds(510, 200, 70, 20);

        jLabel105.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel105.setText("CEP: ");
        jPanel22.add(jLabel105);
        jLabel105.setBounds(670, 200, 110, 20);

        jLabel106.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel106.setText("Código: ");
        jPanel22.add(jLabel106);
        jLabel106.setBounds(80, 10, 80, 20);

        jLabel107.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel107.setText("Data Nascimento: ");
        jPanel22.add(jLabel107);
        jLabel107.setBounds(650, 70, 140, 20);

        jLabel108.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel108.setText("Número: ");
        jPanel22.add(jLabel108);
        jLabel108.setBounds(670, 160, 110, 20);

        jLabel109.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel109.setText("Insc. Estadual:");
        jPanel22.add(jLabel109);
        jLabel109.setBounds(650, 50, 140, 20);

        jLabel110.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel110.setText("Bairro: ");
        jPanel22.add(jLabel110);
        jLabel110.setBounds(20, 180, 100, 20);

        jLabel111.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel111.setText("Logradouro: ");
        jPanel22.add(jLabel111);
        jLabel111.setBounds(20, 160, 100, 20);

        jLabel112.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel112.setText("Complemento: ");
        jPanel22.add(jLabel112);
        jLabel112.setBounds(670, 180, 110, 20);

        jLabel113.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel113.setText("Cidade: ");
        jPanel22.add(jLabel113);
        jLabel113.setBounds(20, 200, 100, 20);

        jLabel114.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel114.setBorder(javax.swing.BorderFactory.createTitledBorder("Endeço:"));
        jPanel22.add(jLabel114);
        jLabel114.setBounds(10, 130, 920, 110);

        jLabel115.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel115.setText("CPF/CNPJ: ");
        jPanel22.add(jLabel115);
        jLabel115.setBounds(80, 30, 80, 20);
        jPanel22.add(jTextField78);
        jTextField78.setBounds(790, 70, 130, 20);
        jPanel22.add(jTextField79);
        jTextField79.setBounds(790, 30, 130, 20);
        jPanel22.add(jTextField80);
        jTextField80.setBounds(790, 50, 130, 20);

        jLabel116.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel116.setText("Nome/Razão Socia: ");
        jPanel22.add(jLabel116);
        jLabel116.setBounds(10, 50, 150, 20);

        jLabel117.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel117.setText("Insc. Munícipal:");
        jPanel22.add(jLabel117);
        jLabel117.setBounds(650, 30, 140, 20);

        jPanel21.add(jPanel22);
        jPanel22.setBounds(0, 0, 0, 0);

        tabProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Custo Produto (m²)", "Mão de Obra (m²)", "Custo Empresa (m² / hora)", "Custo Serviço (m²)", "Margem de Lucro (%)", "Valor Unitário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabProdutoMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(tabProduto);
        if (tabProduto.getColumnModel().getColumnCount() > 0) {
            tabProduto.getColumnModel().getColumn(0).setPreferredWidth(15);
            tabProduto.getColumnModel().getColumn(1).setPreferredWidth(150);
            tabProduto.getColumnModel().getColumn(7).setPreferredWidth(30);
        }

        jPanel21.add(jScrollPane12);
        jScrollPane12.setBounds(20, 100, 930, 310);

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));

        ultimo1.setText(">>||");
        ultimo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimo1ActionPerformed(evt);
            }
        });

        proximo1.setText(">>");
        proximo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximo1ActionPerformed(evt);
            }
        });

        anterior1.setText("<<");
        anterior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anterior1ActionPerformed(evt);
            }
        });

        inicio1.setText("||<<");
        inicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(inicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anterior1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(proximo1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ultimo1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(anterior1)
                        .addComponent(inicio1))
                    .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(proximo1)
                        .addComponent(ultimo1)))
                .addGap(23, 23, 23))
        );

        jPanel21.add(jPanel23);
        jPanel23.setBounds(280, 430, 430, 40);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("CADASTRO DE PRODUTO");
        jPanel21.add(jLabel11);
        jLabel11.setBounds(0, 0, 970, 70);

        jLabel12.setText("Produtos Cadastrados");
        jPanel21.add(jLabel12);
        jLabel12.setBounds(20, 80, 210, 14);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1001, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 981, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(126, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Produtos Cadastrados", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void codProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codProdutoFocusLost
        try {
            produto = produtoDao.getPorCodigo(ValidarValor.getLong(codProduto.getText()));
            if (produto != null) {
                descProduto.setText(produto.getDescricao());
            } else {
                produto = new Produto();
                descProduto.setText("");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_codProdutoFocusLost

    private void descProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descProdutoKeyReleased
        try {
            List<Produto> merged = produtoDao.getList(15, "select e from Produto e where 1=1 and REPLACE(REPLACE(REPLACE(trim(e.descricao),'.',''),'-',''),' ', '') "
                    + " like ?1 order by e.descricao", descProduto.getText().trim().toLowerCase().replace(".", "").replace("-", "").trim() + "%");
            lista.clear();
            lista.addAll(merged);
        } catch (Exception e) {
            System.out.println("Ocorreu um erro ao tentar pesquisar produtos. Erro: " + e);
        }
    }//GEN-LAST:event_descProdutoKeyReleased

    private void atualizarTabela() {

        DefaultTableModel model = (DefaultTableModel) tabProduto.getModel();
        removeLinhas(tabProduto);

        List<?> lv;

        lv = cnvProduto.getLista();

        if (lv != null && !lv.isEmpty()) {

            for (Object o : lv) {
                Object[] os = (Object[]) o;
                model.addRow(os);
                //Colocar tamanho nas colunas

            }
        }
    }

    public static void removeLinhas(JTable table) {
        int n = table.getRowCount();

        DefaultTableModel model = (DefaultTableModel) table.getModel();

        for (int i = n - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }


    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        try {
            codProduto.setText("" + produtoDao.getNextItem());
            codProduto.setEnabled(false);
            limparCampos();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btNovoActionPerformed

    private void limparCampos() {
        try {

            descProduto.setText("");
            produto = new Produto();
            custoProduto.setText("0,00");
            maoDeObra.setText("0,00");
            custoEmpresa.setText("0,00");
            custoServico.setText("0,00");
            margemLucro.setText("0,00");
            valorUnitario.setText("0,00");
            removeLinhas(tabProduto);
            removeLinhas(tabComposicao);

        } catch (Exception e) {
        }
    }


    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        try {
            if (produto == null) {
                produto = new Produto();
                produto.setDataCadastro(new Date());
                produto.setDataAtualizacao(new Date());
            } else {
                produto.setDataAtualizacao(new Date());
            }

            produto.setCodProduto(Long.parseLong(codProduto.getText()));
            produto.setDescricao(descProduto.getText());

            produto.setValorProdutoM2(ValidarValor.getDouble(custoProduto.getText()));
            produto.setMaoDeObra(ValidarValor.getDouble(maoDeObra.getText()));
            produto.setCustoEmpresa(ValidarValor.getDouble(custoEmpresa.getText()));
            produto.setCustoTotal(ValidarValor.getDouble(custoServico.getText()));
            produto.setMargemLucro(ValidarValor.getDouble(margemLucro.getText()));
            produto.setValorUnitario(ValidarValor.getDouble(valorUnitario.getText()));

            if (produtoDao.salvar(produto) != null) {
                JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
            }

            //salvar composição /////////////////////////////////////////////////////
            DefaultTableModel model = (DefaultTableModel) tabComposicao.getModel();
            int i = 0;

            for (i = 0; i < model.getRowCount(); i++) {

                composicaoProduto = new ComposicaoProduto();

                composicaoProduto.setCodComposicaoProduto(composicaoDao.getNextItem());
                composicaoProduto.setProduto(produto);
                composicaoProduto.setMaterial(materialDao.getPorCodigo((Long) model.getValueAt(i, 0)));

            }

            ////////////////////////////////////////////////////////////////////////////
            codProduto.setEnabled(true);
            atualizarTabela();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao salvar produto. Erro: " + e);
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        try {
            if (produto == null) {
                throw new Exception("Erro: produto inválido!");
            }
            int op = 0;
            JOptionPane.showConfirmDialog(null, "Deseja realmente excluir produto selecionado? \n A Composição do produto também será excluída!", "CONFIRMAÇÃO DE EXCLUSÃO", op);

            // considerando 0 como sim
            if (op == 0) {

                produtoDao.delete(produto);

                codProduto.setText("");
                descProduto.setText("");
                atualizarTabela();

            } else {
                return;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir produto. Erro: " + e);
        }
    }//GEN-LAST:event_btExcluirActionPerformed


    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSairActionPerformed

    private void quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeActionPerformed

    private void codMaterialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codMaterialFocusLost
        try {
            material = materialDao.getPorCodigo(ValidarValor.getLong(codMaterial.getText()));
            if (material == null) {
                descMaterial.setText("");
                quantidade.setText("0,00");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }        // 
    }//GEN-LAST:event_codMaterialFocusLost

    private void descMaterialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descMaterialKeyReleased
        try {
            List<Material> merged = materialDao.getList(15, "select e from Material e where 1=1 and REPLACE(REPLACE(REPLACE(trim(e.descricao),'.',''),'-',''),' ', '') "
                    + " like ?1 order by e.descricao", descMaterial.getText().trim().toLowerCase().replace(".", "").replace("-", "").trim() + "%");
            listaMaterial.clear();
            listaMaterial.addAll(merged);

            quantidade.setText("0,00");
        } catch (Exception e) {
            System.out.println("Ocorreu um erro ao tentar pesquisar materials. Erro: " + e);
        }
    }//GEN-LAST:event_descMaterialKeyReleased

    private void btAddMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddMaterialActionPerformed
        try {
            if (codMaterial.getText().equals("") || descMaterial.getText().equals("") || material == null) {
                throw new Exception("Selecione um material válido!");
            }

            if (quantidade.getText().equals("0,00") || ValidarValor.getDouble(quantidade.getText()) <= 0) {
                throw new Exception("Informe a quantidade do material !");
            }

            DefaultTableModel model = (DefaultTableModel) tabComposicao.getModel();

            Object[] os = new Object[4];
            os[0] = codMaterial.getText();
            os[1] = descMaterial.getText();
            os[2] = material.getPrecoCustoTotal();
            os[3] = ValidarValor.getDouble(quantidade.getText());
            os[4] = ((Double) os[3]) * ((Double) os[2]);

            model.addRow(os);

            msgMaterial.setVisible(true);
            atualizaCustoMateriais();
            atualizaValorTotalProduto();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btAddMaterialActionPerformed

    private void maoDeObraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_maoDeObraFocusLost
        atualizaCustoMateriais();
        atualizaValorTotalProduto();

    }//GEN-LAST:event_maoDeObraFocusLost

    private void custoEmpresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_custoEmpresaFocusLost
        atualizaCustoMateriais();
        atualizaValorTotalProduto();
    }//GEN-LAST:event_custoEmpresaFocusLost

    private void margemLucroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_margemLucroFocusLost
        atualizaValorTotalProduto();
    }//GEN-LAST:event_margemLucroFocusLost

    private void tabProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabProdutoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabProdutoMouseClicked

    private void ultimo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ultimo1ActionPerformed

    private void proximo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proximo1ActionPerformed

    private void anterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anterior1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anterior1ActionPerformed

    private void inicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inicio1ActionPerformed

    private void atualizaCustoMateriais() {
        DefaultTableModel model = (DefaultTableModel) tabComposicao.getModel();
        int i = 0;
        Double soma = 0.0;
        try {
            for (i = 0; i < model.getRowCount(); i++) {
                soma = soma + (Double) model.getValueAt(i, 4);
            }
            custoProduto.setText("" + soma);

        } catch (Exception e) {
            e.printStackTrace();
            custoProduto.setText("0,00");
        }
    }

    private void atualizaValorTotalProduto() {

        Double custo = 0.0;
        try {
            custo = (ValidarValor.getDouble(custoProduto.getText()) + ValidarValor.getDouble(maoDeObra.getText()) + ValidarValor.getDouble(custoEmpresa.getText()));

            valorUnitario.setText("" + ((custo * (ValidarValor.getDouble(margemLucro.getText()))) / 100));
        } catch (Exception e) {
            valorUnitario.setText("" + custoProduto.getText());
            e.printStackTrace();

        }
    }

    private void atualizaCustoServico() {
        try {
            custoServico.setText("" + ValidarValor.getDouble(custoProduto.getText()) + ValidarValor.getDouble(maoDeObra.getText()) + ValidarValor.getDouble(custoEmpresa.getText()));

        } catch (Exception e) {
            custoServico.setText("" + custoProduto.getText());
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior1;
    private javax.swing.JButton btAddMaterial;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField codMaterial;
    private javax.swing.JTextField codProduto;
    private javax.swing.JTextField custoEmpresa;
    private javax.swing.JTextField custoProduto;
    private javax.swing.JTextField custoServico;
    private javax.swing.JTextField descMaterial;
    private javax.swing.JTextField descProduto;
    private javax.swing.JButton inicio1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    private javax.swing.JTextField jTextField66;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField74;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JTextField jTextField78;
    private javax.swing.JTextField jTextField79;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField maoDeObra;
    private javax.swing.JTextField margemLucro;
    private javax.swing.JLabel msgMaterial;
    private javax.swing.JButton proximo1;
    private javax.swing.JTextField quantidade;
    private javax.swing.JTable tabComposicao;
    private javax.swing.JTable tabProduto;
    private javax.swing.JButton ultimo1;
    private javax.swing.JTextField valorUnitario;
    // End of variables declaration//GEN-END:variables
}
